### ISSUE TITLE
Start Contributing | beginner friendly | Start Coding

### ISSUE THREAD

**Issue by ashish-ranjan-dev** [ashish135ranjan/ds-algo-for-interview#1]
Post **important** **Data structures and algorithms concepts**
_Important questions from interview point of view
If any modifications needed . Everyone is welcome to show their interest and enthusiasm
Happy Coding.

**Comment by kashika3101** [comment]
Can i work upon Pancake sorting algorithm in C++ as a part of Hacktoberfest'20?

**Comment by ashish-ranjan-dev** [comment]
> Can i work upon Pancake sorting algorithm in C++ as a part of Hacktoberfest'20?

Yes you can

**Comment by black73** [comment]
Can I add heap sort algorithm in C as a part of Hacktoberfest 2020?

**Comment by ashish-ranjan-dev** [comment]
> Can I add heap sort algorithm in C as a part of Hacktoberfest 2020?

Yes, any kind of algorithms which you find helpful are welcome..

**Comment by sunilgknair051** [comment]
Looking to improve the documentation (landing page) and adding a few pointers for newbies. Please assign or approve.

**Comment by ashish-ranjan-dev** [comment]
> Looking to improve the documentation (landing page) and adding a few pointers for newbies. Please assign or approve.

Go ahead

**Comment by jain-aj** [comment]
I would like to add programming algorithms in C++ that can help beginners. Should I start ?

**Comment by sunilgknair051** [comment]
@ashish-ranjan-dev , thank you accepting the PR. Can you please mark all the accepted PRs (which you think makes sense) as "hacktoberfest-accepted"
Would be helpful.
Thanks!
