### ISSUE TITLE
Open source platform for beginners | Start contributing

### ISSUE THREAD

**Issue by ashish-ranjan-dev** [ashish135ranjan/ds-algo-for-interview#2]
Hey everyone , let's come together and code . Put on some great algorithms and data structures paradigm which you feel can help others

**Comment by yashica-patodia** [comment]
I want to work on this issue,and will implement 0/1 BFS IN CPP

**Comment by ashish-ranjan-dev** [comment]
> I want to work on this issue,and will implement 0/1 BFS IN CPP

go ahead. no one is stopping you

**Comment by afeefaa333** [comment]
I want to add subset sum problem

**Comment by afeefaa333** [comment]
please assign me
